### ISSUE TITLE
invalid reporter "mocha-junit-reporter"

### ISSUE THREAD

**Issue by Aditya18Jain** [devops-recipes/basic-node#9]
**Exception**
mocha test --reporter mocha-junit-reporter
/usr/lib/nodejs/mocha/lib/mocha.js:137
    if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
                    ^

Error: invalid reporter "mocha-junit-reporter"
    at Mocha.reporter (/usr/lib/nodejs/mocha/lib/mocha.js:137:27)
    at Object.<anonymous> (/usr/lib/nodejs/mocha/bin/_mocha:191:7)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Code used:**
module.exports = {
    mocha: true,
    path: 'tests/',
    mochaConfig: {
      reporter: 'mocha-junit-reporter',
      reporterOptions: {
        mochaFile: './test-results.xml',
      },
    },
    webdriverio: {
    waitforTimeout: 10000,
    baseUrl: 'http://localhost:3001',
    desiredCapabilities: {
      chromeOptions: {
          args: ['--window-size=1366,768'],
/*                download: {
                  default_directory: '/home/aditya/Desktop',
                },
                'download.default_directory': '/home/aditya/Desktop',*/
            },
        },
    },
};

**Comment by a-murphy** [comment]
Since it looks like you are trying to run this locally, perhaps the reporter isn't installed.  Did you run `npm install` first?  If you are having trouble running this on Shippable, could you open a new issue in [Shippable/support](https://github.com/Shippable/support)?  Issues in Shippable/support are more closely watched than this repository.

**Comment by Aditya18Jain** [comment]
Indeed i tried installing that. Because thats the basic requirement of it.
I think you should first clarify the issue before closing instead of just making assumption.

**Comment by Aditya18Jain** [comment]
Anyways i found a far better plugin then this to solve my issue.

**Comment by sandasika** [comment]
Hey @Aditya18Jain . I ran into the same problem. Can you please post the solution you followed to overcome this?
` 
throw new Error('invalid reporter "' + reporter + '"');
^
Error: invalid reporter "mocha-junit-reporter"
    at Mocha.reporter (C:\node_modules\mocha\lib\mocha.js:164:13)
    at Object.<anonymous> (C:\node_modules\mocha\bin\_mocha:208:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
`

Thanks,
Santhosh
